name: Laravel
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run composer install
        run: composer install
      - name: Run yarn
        run: yarn && yarn dev
      - name: Run tests
        run: ./vendor/bin/phpunit
        env:
          APP_ENV: testing
